language: rust
rust:
  - stable
  - beta
  - nightly
before-install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
install:
  - wasm-pack build --target web
script:
  - wasm-pack test --firefox --headless
