name: wasm-pack for rvemu
on: [push]
jobs:
  build:
    name: build
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
    - uses: actions/setup-node@v1
    - name: Install npm
      run: |
        npm install xterm
        npm install install xterm-addon-fit
    - name: Build
      run: wasm-pack build
    - name: Run tests
      run: wasm-pack test --firefox --headless
