name: CI

on: [push]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [nightly]
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install dependencies
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build
      run: make rvemu

    - name: Run tests
      run: make test

    - name: Run xv6
      run: |
        make
        ./target/release/rvemu-cli -k bin/xv6/kernel.bin -f bin/xv6/fs.img > out &
        pid=$!
        sleep 60
        kill $pid
        grep -q "init: starting sh" ./out
